import type { CardProfile } from '../types';

export const cards: CardProfile[] = [
  {
    id: 'basketball-phenom',
    index: '01',
    player: 'Jalen Quill',
    monogram: 'JQ',
    sport: 'Basketball',
    archetype: 'The Vertical Phenom',
    era: 'Contemporary Kinetic / 2026',
    title: 'Above the Fold',
    accent: '#ff624c',
    accentSecondary: '#5577ff',
    ink: '#f2efe8',
    background: '#11141b',
    artworkPath: 'https://cdn.mint.gg/images/xn7fxfx36ezz85jesan7q4eadd8ah4pj/dynasty-index-01-basketball-phenom-art-58bd4c-fd1b238159d44806.png',
    treatment: 'prismatic',
    treatmentLabel: 'Prismatic foil + clear overlay',
    rarity: 'Crown Spectrum',
    edition: '018 / 125',
    grade: '9.8',
    gradeLabel: 'Gem Archive',
    material: 'Triple-layer chrome stock / acetate veil',
    provenance: 'Recorded during the fictional Meridian Invitational, after a 41-point debut beneath the east gallery lights.',
    collectorNotes: 'A diagonal micro-prism field crosses the image only as the key light passes the lower edge. The acetate veil carries the collection index independently of the printed stock.',
    stats: [
      { label: 'PTS', value: '31.8' },
      { label: 'REB', value: '8.4' },
      { label: 'AST', value: '6.9' },
      { label: 'VERT', value: '46.2″' },
    ],
    lighting: { key: '#a9c6ff', rim: '#ff5e48', fill: '#6a7cff', exposure: 1.05, keyIntensity: 6.1 },
    camera: { yaw: -0.08, pitch: 0.02, distance: 6.35, fov: 33 },
    atmosphere: '#697ea5',
  },
  {
    id: 'football-quarterback',
    index: '02',
    player: 'Mara Voss',
    monogram: 'MV',
    sport: 'Football',
    archetype: 'The Field Architect',
    era: 'Broadcast Technical / 1978',
    title: 'Read No. Four',
    accent: '#d9a45f',
    accentSecondary: '#203a5a',
    ink: '#f2ecdf',
    background: '#121a24',
    artworkPath: 'https://cdn.mint.gg/images/xn78frhj5f9wd0rkaj6t69xsxh8agy50/dynasty-index-02-quarterback-art-06bab6-ae69518118e0ac22.png',
    treatment: 'metallic',
    treatmentLabel: 'Embossed type + brushed metallic ink',
    rarity: 'Signal Proof',
    edition: '084 / 199',
    grade: '9.6',
    gradeLabel: 'Museum Mint',
    material: 'Dense black stock / bronze pressure foil',
    provenance: 'A fictional fourth-quarter study from Voss’s undefeated North Meridian campaign, archived from a silent sideline feed.',
    collectorNotes: 'The play grid is pressed below the surface while the bronze read-path sits above it. At shallow angles the two relief directions split into distinct highlights.',
    stats: [
      { label: 'CMP', value: '72.4%' },
      { label: 'YDS', value: '4,612' },
      { label: 'TD', value: '38' },
      { label: 'QBR', value: '118.7' },
    ],
    lighting: { key: '#ffd9a2', rim: '#6a92bc', fill: '#544a43', exposure: 0.98, keyIntensity: 5.7 },
    camera: { yaw: 0.07, pitch: -0.015, distance: 6.45, fov: 33.5 },
    atmosphere: '#675c52',
  },
  {
    id: 'baseball-slugger',
    index: '03',
    player: 'Diego Vale',
    monogram: 'DV',
    sport: 'Baseball',
    archetype: 'The Long-Ball Craftsman',
    era: 'Archival Press / 1936',
    title: 'Distance, Held',
    accent: '#943c33',
    accentSecondary: '#5d9b9a',
    ink: '#201d1a',
    background: '#d7c9ab',
    artworkPath: 'https://cdn.mint.gg/images/xn77tbfx6y3jzc9v9q2p9qf0en8agpyx/dynasty-index-03-baseball-slugger-art-4394e5-b8e6ee9a017dd9c8.png',
    treatment: 'archival',
    treatmentLabel: 'Cotton paper + letterpress impression',
    rarity: 'Archive Pull',
    edition: '041 / 250',
    grade: '9.3',
    gradeLabel: 'Heritage Fine',
    material: 'Uncoated rag stock / two-pass mineral ink',
    provenance: 'Printed from a fictional spring-training negative discovered in the Vale workshop ledger, plate dated 17 March 1936.',
    collectorNotes: 'The quietest card in the set. Cotton fibers break the solid ink at macro distance, while the edition seal uses a deliberately uneven oxblood strike.',
    stats: [
      { label: 'AVG', value: '.322' },
      { label: 'HR', value: '47' },
      { label: 'RBI', value: '128' },
      { label: 'SLG', value: '.641' },
    ],
    lighting: { key: '#ffe7bc', rim: '#85b7b5', fill: '#8c725b', exposure: 1.12, keyIntensity: 5.1 },
    camera: { yaw: -0.045, pitch: 0.025, distance: 6.3, fov: 32.5 },
    atmosphere: '#aa8f70',
  },
  {
    id: 'soccer-playmaker',
    index: '04',
    player: 'Noa Serein',
    monogram: 'NS',
    sport: 'Soccer',
    archetype: 'The Space Maker',
    era: 'International Modernist / 1994',
    title: 'Between Lines',
    accent: '#31b77d',
    accentSecondary: '#8456c8',
    ink: '#eff2e9',
    background: '#151a19',
    artworkPath: 'https://cdn.mint.gg/images/xn762crpc8jvx60scqt159fadx8agf40/dynasty-index-04-soccer-playmaker-art-acc92e-bd1dd90ecd034eae.png',
    treatment: 'refractive',
    treatmentLabel: 'Refractive border + transparent register',
    rarity: 'Continental Shift',
    edition: '062 / 150',
    grade: '9.7',
    gradeLabel: 'Gem Archive',
    material: 'Satin black stock / indexed clear film',
    provenance: 'A fictional match study charting Serein’s twelve-touch sequence before the winning pass at the Atrium Cup final.',
    collectorNotes: 'A clear registration layer is intentionally offset by half a millimeter. The emerald perimeter refracts into violet when seen from the card edge.',
    stats: [
      { label: 'AST', value: '19' },
      { label: 'KEY', value: '3.8' },
      { label: 'PASS', value: '91.2%' },
      { label: 'xA', value: '14.7' },
    ],
    lighting: { key: '#b8ffe2', rim: '#a985ff', fill: '#426b5a', exposure: 1.02, keyIntensity: 5.9 },
    camera: { yaw: 0.06, pitch: 0.018, distance: 6.4, fov: 33 },
    atmosphere: '#4d7468',
  },
  {
    id: 'hockey-goaltender',
    index: '05',
    player: 'Ilya Rook',
    monogram: 'IR',
    sport: 'Hockey',
    archetype: 'The Last Geometry',
    era: 'Equipment Blueprint / 1985',
    title: 'Angles of Refusal',
    accent: '#71d2d1',
    accentSecondary: '#d5dce1',
    ink: '#e8f4f3',
    background: '#122026',
    artworkPath: 'https://cdn.mint.gg/images/xn75t395f0ve50hbrqzzy1338d8agv1a/dynasty-index-05-hockey-goaltender-art-f9d1a1-4d0478aa47af4f68.png',
    treatment: 'frosted',
    treatmentLabel: 'Frosted acetate + cold-silver foil',
    rarity: 'Zero Aperture',
    edition: '009 / 099',
    grade: '9.9',
    gradeLabel: 'Vault Perfect',
    material: 'Frosted PET veil / silver technical ink',
    provenance: 'Catalogued after Rook’s fictional 63-save winter exhibition, with every shot path reconstructed from rink telemetry.',
    collectorNotes: 'The mask and crease geometry are printed on separate depths. A frosted veil softens the portrait until the card is tilted toward the inspection blade.',
    stats: [
      { label: 'SV%', value: '.938' },
      { label: 'GAA', value: '1.82' },
      { label: 'SO', value: '11' },
      { label: 'SAVES', value: '1,884' },
    ],
    lighting: { key: '#caffff', rim: '#dce8f0', fill: '#3c6872', exposure: 1.0, keyIntensity: 6.4 },
    camera: { yaw: -0.065, pitch: -0.012, distance: 6.32, fov: 32.8 },
    atmosphere: '#54777f',
  },
  {
    id: 'track-champion',
    index: '06',
    player: 'Amara Kestrel',
    monogram: 'AK',
    sport: 'Track',
    archetype: 'The Time Breaker',
    era: 'Chronometric Future / 2040',
    title: 'After the Clock',
    accent: '#f04491',
    accentSecondary: '#ffb84d',
    ink: '#f5eee8',
    background: '#120f16',
    artworkPath: 'https://cdn.mint.gg/images/xn77nn7m0n5n8mq7m1406mfars8agfph/dynasty-index-06-track-champion-art-9b8849-d8a5fc3664f3a3ed.png',
    treatment: 'microline',
    treatmentLabel: 'Iridescent microline + selective gloss',
    rarity: 'Worldline One',
    edition: '001 / 075',
    grade: '10.0',
    gradeLabel: 'Reference Specimen',
    material: 'Carbon-black stock / spectral micro-etch',
    provenance: 'The fictional first card struck from Kestrel’s sub-10 Meridian Circuit run, encoded against the official photo-finish trace.',
    collectorNotes: 'The line field is etched at two frequencies: one resolves as speed, the other as a spectral color shift. Edition one carries a flush black stamp visible only in raking light.',
    stats: [
      { label: '100M', value: '9.84' },
      { label: '200M', value: '19.71' },
      { label: 'R.T.', value: '.128' },
      { label: 'WINS', value: '18' },
    ],
    lighting: { key: '#ffd6ea', rim: '#ffbd63', fill: '#6e4562', exposure: 1.04, keyIntensity: 6.2 },
    camera: { yaw: 0.035, pitch: 0.015, distance: 6.25, fov: 32.5 },
    atmosphere: '#74455f',
  },
];

export const getCard = (index: number): CardProfile => cards[(index + cards.length) % cards.length];
